package org.javierub.views;


import org.javierub.library.DAOUsersImpl;
import org.javierub.library.DashBoard;
import org.javierub.models.Users;

import javax.swing.*;
import java.awt.Color;

public class UpUsers extends javax.swing.JPanel {
    boolean isEdition = false;
    Users userEdited = null;

    public UpUsers() {
        initComponents();
        InitStyles();
    }

    public UpUsers(Users userEdited) {
        initComponents();
        isEdition = true;
        this.userEdited = userEdited;
        InitStyles();
    }


    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);

        nameTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario.");
        apPTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del usuario.");
        apMTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del usuario.");
        mailTxt.putClientProperty("JTextField.placeholderText", "Ingrese el correo del usuario.");
        phoneTxt.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono del usuario.");

        if (isEdition) {
            title.setText("Editar Usuario");
            btn_register.setText("Guardar");

            if (userEdited != null) {
                nameTxt.setText(userEdited.getName());
                apPTxt.setText(userEdited.getLast_name_p());
                apMTxt.setText(userEdited.getLast_name_m());
                mailTxt.setText(userEdited.getDomicilio());
                phoneTxt.setText(userEdited.getTelefono());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        apPLbl = new javax.swing.JLabel();
        apPTxt = new javax.swing.JTextField();
        apMLbl = new javax.swing.JLabel();
        apMTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mailLbl = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        phoneLbl = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(738, 429));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(738, 429));

        title.setText("Registrar nuevo Usuario");

        nameLbl.setText("Nombre");

        apPLbl.setText("Apellido Paterno");

        apMLbl.setText("Apellido Materno");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        mailLbl.setText("Correo");

        mailTxt.setToolTipText("");

        btn_register.setBackground(new java.awt.Color(18, 90, 173));
        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Registrar");
        btn_register.setBorderPainted(false);
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        phoneLbl.setText("Teléfono");

        phoneTxt.setToolTipText("");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(223, 223, 223))
                            .addComponent(nameTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(apPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(182, 182, 182))
                            .addComponent(apPTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(apMLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(180, 180, 180))
                            .addComponent(apMTxt))
                        .addGap(68, 68, 68)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mailTxt)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(mailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(220, 220, 220))
                                    .addComponent(phoneTxt)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(218, 218, 218)))
                                .addGap(72, 72, 72))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(494, 494, 494))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(apPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(apMLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(mailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(164, 164, 164))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 710, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Users user;
        DAOUsersImpl dao = new DAOUsersImpl();
        String name = nameTxt.getText();
        String surname_daddy = apPTxt.getText();
        String surname_mommy = apMTxt.getText();
        String address = mailTxt.getText();
        String phone = phoneTxt.getText();

        if(name.isEmpty() || surname_daddy.isEmpty() || surname_mommy.isEmpty() || address.isEmpty() || phone.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.\n", "AVISO", JOptionPane.WARNING_MESSAGE);
            nameTxt.requestFocus(); // Pone el foco en el campo de texto.
            return;
        }

        if(!esCorreoValido(address)){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduzca el correo correctamente.\n", "AVISO", JOptionPane.WARNING_MESSAGE);
            mailTxt.requestFocus(); // Pone el foco en el campo de texto.
            return;
        }

        if(!esTelefonoValido(phone) ){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduzca el número correctamente.\n", "AVISO", JOptionPane.WARNING_MESSAGE);
            phoneTxt.requestFocus();
            return;
        }

        if(isEdition) {
            user = userEdited;
        } else {
            user = new Users();
        }
        user.setName(name);
        user.setLast_name_p(surname_daddy);
        user.setLast_name_m(surname_mommy);
        user.setDomicilio(address);
        user.setTelefono(phone);

        try{
            if(isEdition) {
                dao.update(userEdited);
                javax.swing.JOptionPane.showMessageDialog(this, "El usuario se actualizó correctamente.\n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                DashBoard.showJPanel(new org.javierub.views.Users());
            }

            if(!isEdition){
                dao.insert(user);
                javax.swing.JOptionPane.showMessageDialog(this, "El usuario se registró correctamente.\n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            }

            nameTxt.setText("");
            apPTxt.setText("");
            apMTxt.setText("");
            mailTxt.setText("");
            phoneTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar al usuario, inténtelo de nuevo más tarde.\n", "AVISO", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    public boolean esCorreoValido(String correo) {
        String regex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$"; // Expresión regular para validar correos electrónicos.
        return correo.matches(regex);
    }

    public boolean esTelefonoValido(String telefono) {
        // Esta expresión regular permite paréntesis, espacios, guiones y puntos, y espera entre 7 a 15 dígitos.
        String regex = "^\\+?([0-9]{1,3})?[-.\\s]?\\(?([0-9]{2,3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{2,4})[-.\\s]?([0-9]{2,4})$"; // Expresión regular para validar números telefónicos.
        return telefono.matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apMLbl;
    private javax.swing.JTextField apMTxt;
    private javax.swing.JLabel apPLbl;
    private javax.swing.JTextField apPTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_register;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mailLbl;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}